name: Release to NuGet

on:
  push:
    branches:
      - main
   
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NuGetDirectory: ${{ github.workspace}}/nuget
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build src/TestingCommons.sln -c Release 
    - name: Test
      run: dotnet test src/TestingCommons.UnitTests/TestingCommons.UnitTests.csproj -c Release --no-build
    - name: Pack nugets
      run: dotnet pack src/TestingCommons.Azure/TestingCommons.Azure.csproj -c Release --no-build --output ${{ env.NuGetDirectory }}
    - name: Pack nugets
      run: dotnet pack src/TestingCommons.Core/TestingCommons.Core.csproj -c Release --no-build --output ${{ env.NuGetDirectory }}
    - name: Pack nugets
      run: dotnet pack src/TestingCommons.MongoDb/TestingCommons.MongoDb.csproj -c Release --no-build --output ${{ env.NuGetDirectory }}
    - name: Pack nugets
      run: dotnet pack src/TestingCommons.NewRelic/TestingCommons.NewRelic.csproj -c Release --no-build --output ${{ env.NuGetDirectory }}
    - name: Pack nugets
      run: dotnet pack src/TestingCommons.Reqnroll/TestingCommons.Reqnroll.csproj -c Release --no-build --output ${{ env.NuGetDirectory }}
    - name: Pack nugets
      run: dotnet pack src/TestingCommons.RabbitMq/TestingCommons.RabbitMq.csproj -c Release --no-build --output ${{ env.NuGetDirectory }}
    - name: Pack nugets
      run: dotnet pack src/TestingCommons.RestApiClient/TestingCommons.RestApiClient.csproj -c Release --no-build --output ${{ env.NuGetDirectory }}
    - name: Publish NuGet package
      shell: pwsh
      run: |
        foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
            dotnet nuget push $file --api-key "${{ secrets.nuget_api_key }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
        }
